POST http://localhost:8080/api/employees HTTP/1.1
content-type: application/json

 {
    "firstName": "Mai",
    "lastName": "Phat",
    "email": "Phat@gmail.com",
    "phoneNumber": "0904112123",
    "address": "38 Yên Bái",
    "birthDay": "1995-09-02",
    "password": "Mypass123",
    "avatar": "https://avatars.githubusercontent.com/u/97165289",
    "role": "Admin"
}

###
DELETE   http://localhost:8080/api/employees/65f3ad013ffb3e2a2636a0a9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYzYWQ4YjJiY2QyMGYyMjE4MDk0MzUiLCJlbWFpbCI6IlRyb25nQGdtYWlsLmNvbSIsImlhdCI6MTcxMDQ2ODUwNiwiZXhwIjoxNzExNzY0NTA2fQ.frVHD9IaH2Fvq6_YSkyGBRFI2QklzbQJk-cQd1lcUUo