###
POST http://localhost:8080/api/products HTTP/1.1
content-type: application/json

{
    "product_name": "iPhone 14 Pro Max 128GB",
    "price": 1600,
    "discount":0,
    "stock":5,
    "description": "",
    "categoryId": "6604da64e85af424b9b3fc32",
    "brandId": "65f7adac9ee0c5e89f120fe6",
    "thumbnail": [{"url":"https://cdn11.dienmaycholon.vn/filewebdmclnew/public/userupload/files/dien-thoai-camera-tot-nhat-1.png"},
    {"url": "https://cdn11.dienmaycholon.vn/filewebdmclnew/public//userupload/images/dien-thoai-Samsung-Galaxy-S10-Plus-1.jpg"}]

}

###
PATCH  http://localhost:8080/api/products/660520c73c31a634e96fc73f HTTP/1.1
content-type: application/json

{
    
    "product_name": "iPhone 14 Pro Max 128GB",
    "price": 1600,
    "discount":0,
    "stock":5,
    "description": "",
    "categoryId": "6604da64e85af424b9b3fc32",
    "brandId": "65f7adac9ee0c5e89f120fe6",
    "thumbnail": [{"url":"https://cdn11.dienmaycholon.vn/filewebdmclnew/public/userupload/files/dien-thoai-camera-tot-nhat-1.png"},
    {"url": "https://cdn11.dienmaycholon.vn/filewebdmclnew/public//userupload/images/dien-thoai-Samsung-Galaxy-S10-Plus-1.jpg"}]
}

###

DELETE http://localhost:8080/api/products/66063602ad6407b0a368883a HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYzYWE5ZDhmYjM4NmFjNmYzZDNlNmMiLCJlbWFpbCI6IlBoYXRAZ21haWwuY29tIiwiaWF0IjoxNzEwOTg3NjU1LCJleHAiOjE3MTIyODM2NTV9.Ez1vR9GQFuXetd_82m6f5gsT76JXzv6ks8j_C_tplyQ